export type Product = {
    id: string;
    name: string;
    slug: string;
    description: string;
    shortDescription: string;
    price: number;
    originalPrice?: number;
    discount?: number;
    category: string;
    brand: string;
    images: string[];
    rating: number;
    reviewCount: number;
    sizes: string[];
    colors: { name: string; hex: string }[];
    stock: number;
    stockPerVariant: Record<string, number>;
    tags: string[];
    isNew?: boolean;
    isBestSeller?: boolean;
    isFeatured?: boolean;
    material?: string;
    specifications?: Record<string, string>;
};

export type Category = {
    id: string;
    name: string;
    slug: string;
    image: string;
    count: number;
    description: string;
};

export type Review = {
    id: string;
    productId: string;
    userId: string;
    userName: string;
    avatar: string;
    rating: number;
    title: string;
    comment: string;
    date: string;
    helpful: number;
    verified: boolean;
};

export type User = {
    id: string;
    name: string;
    email: string;
    avatar: string;
    phone: string;
    dob: string;
    addresses: Address[];
};

export type Address = {
    id: string;
    name: string;
    street: string;
    city: string;
    state: string;
    zip: string;
    country: string;
    isDefault: boolean;
};

export type Order = {
    id: string;
    userId: string;
    items: { productId: string; quantity: number; price: number; size: string; color: string }[];
    total: number;
    status: "Processing" | "Shipped" | "Delivered" | "Cancelled";
    date: string;
    trackingNumber?: string;
    shippingAddress: Address;
};

// -------- Mock Images (Unsplash) --------
const fashionImages = {
    men: [
        "https://images.unsplash.com/photo-1594938298603-c8148c4b942c?w=800&q=80",
        "https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&q=80",
        "https://images.unsplash.com/photo-1593030761757-71faaab4b6e8?w=800&q=80",
        "https://images.unsplash.com/photo-1578932750294-f5075e85f44a?w=800&q=80",
        "https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?w=800&q=80",
    ],
    women: [
        "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        "https://images.unsplash.com/photo-1525507119028-ed4ccaebb23d?w=800&q=80",
        "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80",
        "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&q=80",
        "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80",
    ],
    shoes: [
        "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
        "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&q=80",
        "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80",
        "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80",
    ],
    accessories: [
        "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
        "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80",
        "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    ],
    kids: [
        "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&q=80",
        "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800&q=80",
    ],
};

// -------- Products --------
export const products: Product[] = [
    {
        id: "p1",
        name: "Classic Oxford Shirt",
        slug: "classic-oxford-shirt",
        description: "A timeless Oxford shirt crafted from premium 100% cotton. Perfect for both casual and semi-formal occasions. Features a button-down collar, single chest pocket, and a relaxed fit that provides all-day comfort. The fabric is pre-washed for a soft hand feel and to minimize shrinkage.",
        shortDescription: "Premium cotton Oxford shirt with button-down collar",
        price: 79.99,
        originalPrice: 120.00,
        discount: 33,
        category: "men",
        brand: "StyleCo",
        images: fashionImages.men,
        rating: 4.5,
        reviewCount: 128,
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        colors: [
            { name: "White", hex: "#FFFFFF" },
            { name: "Light Blue", hex: "#BFD7FF" },
            { name: "Navy", hex: "#1E3A5F" },
        ],
        stock: 45,
        stockPerVariant: { "M-White": 10, "L-White": 8, "S-Light Blue": 5, "M-Navy": 7 },
        tags: ["oxford", "shirt", "casual", "cotton"],
        isNew: false,
        isBestSeller: true,
        material: "100% Egyptian Cotton",
        specifications: { Material: "100% Egyptian Cotton", Fit: "Regular", Collar: "Button-Down", Care: "Machine wash cold" },
    },
    {
        id: "p2",
        name: "Slim Fit Chino Pants",
        slug: "slim-fit-chino-pants",
        description: "Modern slim-fit chinos made from stretch-cotton blend for exceptional comfort and mobility. A versatile wardrobe essential that transitions effortlessly from office to weekend.",
        shortDescription: "Stretch-cotton slim fit chinos for all occasions",
        price: 89.99,
        originalPrice: undefined,
        discount: undefined,
        category: "men",
        brand: "UrbanEdge",
        images: [fashionImages.men[1], fashionImages.men[2], fashionImages.men[3]],
        rating: 4.3,
        reviewCount: 89,
        sizes: ["28", "30", "32", "34", "36", "38"],
        colors: [
            { name: "Khaki", hex: "#C3B091" },
            { name: "Olive", hex: "#708238" },
            { name: "Navy", hex: "#1E3A5F" },
            { name: "Charcoal", hex: "#36454F" },
        ],
        stock: 62,
        stockPerVariant: { "32-Khaki": 12, "34-Khaki": 10, "30-Navy": 8 },
        tags: ["chino", "pants", "slim fit"],
        isBestSeller: true,
        material: "97% Cotton, 3% Elastane",
        specifications: { Material: "97% Cotton, 3% Elastane", Fit: "Slim", Rise: "Mid", Care: "Machine wash cold" },
    },
    {
        id: "p3",
        name: "Floral Wrap Dress",
        slug: "floral-wrap-dress",
        description: "Effortlessly feminine wrap dress featuring a vibrant floral print. The V-neckline, flutter sleeves, and adjustable tie waist create a flattering silhouette for any body type.",
        shortDescription: "Vibrant floral print wrap dress with V-neckline",
        price: 109.99,
        originalPrice: 159.99,
        discount: 31,
        category: "women",
        brand: "BellaMode",
        images: fashionImages.women,
        rating: 4.8,
        reviewCount: 215,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: [
            { name: "Floral Pink", hex: "#FFB6C1" },
            { name: "Floral Blue", hex: "#ADD8E6" },
            { name: "Floral Green", hex: "#90EE90" },
        ],
        stock: 34,
        stockPerVariant: { "S-Floral Pink": 8, "M-Floral Pink": 6, "S-Floral Blue": 5 },
        tags: ["dress", "floral", "wrap", "summer"],
        isNew: true,
        isFeatured: true,
        material: "100% Viscose",
        specifications: { Material: "100% Viscose", Neckline: "V-Neck", Sleeves: "Flutter", Care: "Hand wash cold" },
    },
    {
        id: "p4",
        name: "High-Rise Skinny Jeans",
        slug: "high-rise-skinny-jeans",
        description: "Ultra-comfortable high-rise skinny jeans with a hint of stretch. The contoured waistband prevents gaping and ensures a perfect fit all day long.",
        shortDescription: "High-rise skinny jeans with stretch comfort",
        price: 95.00,
        originalPrice: undefined,
        discount: undefined,
        category: "women",
        brand: "DenimLab",
        images: [fashionImages.women[1], fashionImages.women[2], fashionImages.women[3]],
        rating: 4.6,
        reviewCount: 312,
        sizes: ["24", "26", "28", "30", "32"],
        colors: [
            { name: "Dark Wash", hex: "#1B2A4A" },
            { name: "Medium Wash", hex: "#5B8DB8" },
            { name: "Light Wash", hex: "#B8D4E8" },
            { name: "Black", hex: "#141414" },
        ],
        stock: 78,
        stockPerVariant: { "28-Dark Wash": 15, "26-Dark Wash": 12, "28-Black": 10 },
        tags: ["jeans", "denim", "skinny", "high-rise"],
        isBestSeller: true,
        material: "92% Cotton, 6% Polyester, 2% Elastane",
        specifications: { Material: "92% Cotton, 6% Polyester, 2% Elastane", Rise: "High", Fit: "Skinny", Care: "Machine wash cold inside out" },
    },
    {
        id: "p5",
        name: "Air Runner Pro Sneakers",
        slug: "air-runner-pro-sneakers",
        description: "Engineered for peak performance, the Air Runner Pro features responsive cushioning, breathable mesh upper, and a durable rubber outsole. Perfect for running, training, or everyday wear.",
        shortDescription: "Performance sneakers with responsive cushioning",
        price: 149.99,
        originalPrice: 189.99,
        discount: 21,
        category: "shoes",
        brand: "SwiftStep",
        images: fashionImages.shoes,
        rating: 4.7,
        reviewCount: 445,
        sizes: ["7", "8", "9", "10", "11", "12", "13"],
        colors: [
            { name: "White/Blue", hex: "#E8F4FD" },
            { name: "Black/Red", hex: "#1A1A1A" },
            { name: "Grey/Green", hex: "#9CA3AF" },
        ],
        stock: 88,
        stockPerVariant: { "10-White/Blue": 15, "9-White/Blue": 12, "11-Black/Red": 8 },
        tags: ["sneakers", "running", "athletic", "comfortable"],
        isNew: true,
        isBestSeller: true,
        isFeatured: true,
        material: "Breathable Mesh, Rubber Sole",
        specifications: { Upper: "Breathable Mesh", Sole: "Rubber", Technology: "Air Cushion", Weight: "280g" },
    },
    {
        id: "p6",
        name: "Leather Crossbody Bag",
        slug: "leather-crossbody-bag",
        description: "Handcrafted from full-grain leather, this crossbody bag features an adjustable strap, multiple compartments, and gold-tone hardware. Ages beautifully with everyday use.",
        shortDescription: "Full-grain leather crossbody with gold hardware",
        price: 229.99,
        originalPrice: 299.99,
        discount: 23,
        category: "accessories",
        brand: "LuxCraft",
        images: fashionImages.accessories,
        rating: 4.9,
        reviewCount: 167,
        sizes: ["One Size"],
        colors: [
            { name: "Cognac", hex: "#9B4A11" },
            { name: "Black", hex: "#141414" },
            { name: "Taupe", hex: "#B2A898" },
        ],
        stock: 23,
        stockPerVariant: { "One Size-Cognac": 9, "One Size-Black": 8, "One Size-Taupe": 6 },
        tags: ["bag", "leather", "crossbody", "accessory"],
        isFeatured: true,
        material: "Full-Grain Leather",
        specifications: { Material: "Full-Grain Leather", Hardware: "Gold-tone", Dimensions: "25x18x8 cm", Strap: "Adjustable" },
    },
    {
        id: "p7",
        name: "Kids Adventure Hoodie",
        slug: "kids-adventure-hoodie",
        description: "Super-soft fleece hoodie designed for active kids. Features a kangaroo pocket, adjustable drawstring hood, and reinforced elbows. Machine washable and built to last through all their adventures.",
        shortDescription: "Durable fleece hoodie for active kids",
        price: 45.99,
        originalPrice: undefined,
        discount: undefined,
        category: "kids",
        brand: "TinyTrends",
        images: fashionImages.kids,
        rating: 4.4,
        reviewCount: 73,
        sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y", "11-12Y"],
        colors: [
            { name: "Blue", hex: "#3B82F6" },
            { name: "Red", hex: "#EF4444" },
            { name: "Green", hex: "#22C55E" },
            { name: "Purple", hex: "#A855F7" },
        ],
        stock: 55,
        stockPerVariant: { "7-8Y-Blue": 12, "5-6Y-Red": 10, "9-10Y-Green": 8 },
        tags: ["kids", "hoodie", "fleece", "casual"],
        isNew: true,
        material: "80% Cotton, 20% Polyester Fleece",
        specifications: { Material: "80% Cotton, 20% Polyester Fleece", Pocket: "Kangaroo", Hood: "Adjustable", Care: "Machine wash warm" },
    },
    {
        id: "p8",
        name: "Merino Wool Turtleneck",
        slug: "merino-wool-turtleneck",
        description: "Luxuriously soft merino wool turtleneck sweater. Temperature-regulating fiber keeps you comfortable in varying conditions. A sophisticated layering piece for the colder months.",
        shortDescription: "100% merino wool turtleneck sweater",
        price: 139.99,
        originalPrice: 179.99,
        discount: 22,
        category: "men",
        brand: "WoolCo",
        images: [fashionImages.men[0], fashionImages.men[2], fashionImages.men[4]],
        rating: 4.6,
        reviewCount: 94,
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        colors: [
            { name: "Camel", hex: "#C19A6B" },
            { name: "Charcoal", hex: "#36454F" },
            { name: "Burgundy", hex: "#800020" },
            { name: "Cream", hex: "#FFFDD0" },
        ],
        stock: 41,
        stockPerVariant: { "M-Camel": 10, "L-Charcoal": 8, "S-Cream": 6 },
        tags: ["sweater", "wool", "merino", "turtleneck", "winter"],
        material: "100% Merino Wool",
        specifications: { Material: "100% Merino Wool", Micron: "18.5", Fit: "Regular", Care: "Dry clean or hand wash" },
    },
    {
        id: "p9",
        name: "Linen Summer Blazer",
        slug: "linen-summer-blazer",
        description: "Lightweight linen blazer with a modern slim silhouette. Breathable and wrinkle-resistant, it's the perfect choice for warm-weather events and smart-casual looks.",
        shortDescription: "Lightweight linen blazer for summer occasions",
        price: 199.99,
        originalPrice: 259.99,
        discount: 23,
        category: "men",
        brand: "StyleCo",
        images: [fashionImages.men[2], fashionImages.men[0], fashionImages.men[3]],
        rating: 4.4,
        reviewCount: 56,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: [
            { name: "Beige", hex: "#F5F0E8" },
            { name: "Navy", hex: "#1E3A5F" },
            { name: "Sage", hex: "#8FAF84" },
        ],
        stock: 28,
        stockPerVariant: { "M-Beige": 8, "L-Navy": 6, "S-Sage": 4 },
        tags: ["blazer", "linen", "summer", "formal"],
        isNew: true,
        material: "100% Linen",
        specifications: { Material: "100% Linen", Fit: "Slim", Closure: "2-Button", Care: "Dry clean recommended" },
    },
    {
        id: "p10",
        name: "Silk Slip Dress",
        slug: "silk-slip-dress",
        description: "Elegant slip dress crafted from luxurious silk charmeuse. Features adjustable spaghetti straps, a V-neck, and a bias cut that drapes beautifully over the body. Perfect for evening events.",
        shortDescription: "Luxurious silk charmeuse slip dress",
        price: 189.99,
        originalPrice: undefined,
        discount: undefined,
        category: "women",
        brand: "BellaMode",
        images: [fashionImages.women[2], fashionImages.women[0], fashionImages.women[4]],
        rating: 4.8,
        reviewCount: 143,
        sizes: ["XS", "S", "M", "L"],
        colors: [
            { name: "Champagne", hex: "#F7E7CE" },
            { name: "Midnight Blue", hex: "#003366" },
            { name: "Blush Pink", hex: "#FFB6C1" },
            { name: "Emerald", hex: "#50C878" },
        ],
        stock: 19,
        stockPerVariant: { "S-Champagne": 5, "M-Blush Pink": 4, "XS-Emerald": 3 },
        tags: ["dress", "silk", "evening", "slip"],
        isFeatured: true,
        material: "100% Silk Charmeuse",
        specifications: { Material: "100% Silk Charmeuse", Neckline: "V-Neck", Straps: "Adjustable Spaghetti", Care: "Dry clean only" },
    },
    {
        id: "p11",
        name: "Chelsea Ankle Boots",
        slug: "chelsea-ankle-boots",
        description: "Classic Chelsea boots in premium leather with elastic side panels for easy on-off wear. The stacked heel and pointed toe create a sophisticated look that works with both jeans and dresses.",
        shortDescription: "Premium leather Chelsea boots with stacked heel",
        price: 179.99,
        originalPrice: 229.99,
        discount: 22,
        category: "shoes",
        brand: "FootFlair",
        images: [fashionImages.shoes[1], fashionImages.shoes[0], fashionImages.shoes[2]],
        rating: 4.5,
        reviewCount: 188,
        sizes: ["6", "7", "8", "9", "10", "11"],
        colors: [
            { name: "Black", hex: "#141414" },
            { name: "Tan", hex: "#D2B48C" },
            { name: "Burgundy", hex: "#800020" },
        ],
        stock: 36,
        stockPerVariant: { "7-Black": 10, "8-Black": 9, "7-Tan": 8 },
        tags: ["boots", "chelsea", "leather", "ankle"],
        isBestSeller: true,
        material: "Premium Leather",
        specifications: { Upper: "Premium Leather", Sole: "Leather", Heel: "4cm Stacked", Closure: "Elastic Side Panels" },
    },
    {
        id: "p12",
        name: "Rose Gold Watch",
        slug: "rose-gold-watch",
        description: "Minimalist rose gold watch featuring a Japanese quartz movement, sapphire crystal glass, and a genuine leather strap. Water resistant to 50 meters.",
        shortDescription: "Minimalist rose gold watch with sapphire crystal",
        price: 299.99,
        originalPrice: 399.99,
        discount: 25,
        category: "accessories",
        brand: "TimeCraft",
        images: [fashionImages.accessories[1], fashionImages.accessories[0], fashionImages.accessories[2]],
        rating: 4.9,
        reviewCount: 234,
        sizes: ["One Size"],
        colors: [
            { name: "Rose Gold/Cream", hex: "#B76E79" },
            { name: "Silver/Black", hex: "#C0C0C0" },
            { name: "Gold/Brown", hex: "#FFD700" },
        ],
        stock: 15,
        stockPerVariant: { "One Size-Rose Gold/Cream": 7, "One Size-Silver/Black": 5 },
        tags: ["watch", "jewelry", "minimalist", "rose gold"],
        isFeatured: true,
        isNew: false,
        material: "Stainless Steel, Sapphire Crystal, Leather",
        specifications: { Movement: "Japanese Quartz", Crystal: "Sapphire", Strap: "Genuine Leather", "Water Resistance": "50m" },
    },
    {
        id: "p13",
        name: "Athletic Performance Leggings",
        slug: "athletic-performance-leggings",
        description: "High-performance leggings with moisture-wicking fabric, a wide waistband, and a flatlock seam construction to prevent chafing. Four-way stretch for unrestricted movement.",
        shortDescription: "Moisture-wicking high-performance leggings",
        price: 69.99,
        originalPrice: undefined,
        discount: undefined,
        category: "women",
        brand: "ActiveWear",
        images: [fashionImages.women[3], fashionImages.women[1], fashionImages.women[4]],
        rating: 4.7,
        reviewCount: 389,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: [
            { name: "Black", hex: "#141414" },
            { name: "Midnight Blue", hex: "#003366" },
            { name: "Mauve", hex: "#E0B4B7" },
            { name: "Coral", hex: "#FF6B6B" },
        ],
        stock: 92,
        stockPerVariant: { "S-Black": 20, "M-Black": 18, "L-Midnight Blue": 15 },
        tags: ["leggings", "athletic", "yoga", "gym"],
        isBestSeller: true,
        material: "78% Nylon, 22% Spandex",
        specifications: { Material: "78% Nylon, 22% Spandex", Waistband: "Wide, 4-inch", Seams: "Flatlock", Technology: "Moisture-Wicking" },
    },
    {
        id: "p14",
        name: "Oversized Denim Jacket",
        slug: "oversized-denim-jacket",
        description: "A laid-back denim jacket with an oversized fit and vintage-inspired wash. Features chest pockets, side pockets, and adjustable button cuffs. The perfect layering piece for transitional weather.",
        shortDescription: "Vintage-inspired oversized denim jacket",
        price: 119.99,
        originalPrice: 149.99,
        discount: 20,
        category: "women",
        brand: "DenimLab",
        images: [fashionImages.women[0], fashionImages.women[3], fashionImages.women[2]],
        rating: 4.5,
        reviewCount: 127,
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        colors: [
            { name: "Light Wash", hex: "#B8D4E8" },
            { name: "Medium Wash", hex: "#5B8DB8" },
            { name: "Dark Wash", hex: "#1B2A4A" },
        ],
        stock: 47,
        stockPerVariant: { "S-Light Wash": 12, "M-Light Wash": 10, "L-Medium Wash": 8 },
        tags: ["jacket", "denim", "oversized", "casual"],
        isNew: true,
        material: "100% Cotton Denim",
        specifications: { Material: "100% Cotton Denim", Fit: "Oversized", Pockets: "4", Care: "Machine wash cold inside out" },
    },
    {
        id: "p15",
        name: "Suede Loafer Shoes",
        slug: "suede-loafer-shoes",
        description: "Sophisticated penny loafers in premium suede with a cushioned insole and lug sole. The slip-on design and timeless silhouette make these a versatile wardrobe staple.",
        shortDescription: "Premium suede penny loafers with cushioned insole",
        price: 159.99,
        originalPrice: undefined,
        discount: undefined,
        category: "shoes",
        brand: "FootFlair",
        images: [fashionImages.shoes[2], fashionImages.shoes[3], fashionImages.shoes[0]],
        rating: 4.6,
        reviewCount: 95,
        sizes: ["7", "8", "9", "10", "11", "12"],
        colors: [
            { name: "Sand", hex: "#C2B280" },
            { name: "Forest Green", hex: "#228B22" },
            { name: "Chocolate", hex: "#7B3F00" },
        ],
        stock: 32,
        stockPerVariant: { "9-Sand": 10, "10-Sand": 8, "8-Forest Green": 6 },
        tags: ["loafer", "suede", "shoes", "classic"],
        material: "Premium Suede",
        specifications: { Upper: "Premium Suede", Sole: "Rubber Lug", Lining: "Leather", Insole: "Memory Foam Cushion" },
    },
    {
        id: "p16",
        name: "Cashmere Blend Cardigan",
        slug: "cashmere-blend-cardigan",
        description: "Incredibly soft cashmere-blend cardigan with a relaxed drape and open-front design. Features patch pockets and a ribbed hem for a polished yet effortless look.",
        shortDescription: "Soft cashmere-blend open-front cardigan",
        price: 159.99,
        originalPrice: 210.00,
        discount: 24,
        category: "women",
        brand: "WoolCo",
        images: [fashionImages.women[4], fashionImages.women[1], fashionImages.women[0]],
        rating: 4.7,
        reviewCount: 162,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: [
            { name: "Oatmeal", hex: "#E8DCCA" },
            { name: "Dusty Pink", hex: "#DCAAB0" },
            { name: "Sage Green", hex: "#B2C5B2" },
            { name: "Charcoal", hex: "#36454F" },
        ],
        stock: 38,
        stockPerVariant: { "S-Oatmeal": 10, "M-Oatmeal": 9, "S-Dusty Pink": 7 },
        tags: ["cardigan", "cashmere", "knit", "women", "cozy"],
        isFeatured: true,
        material: "70% Cashmere, 30% Wool",
        specifications: { Material: "70% Cashmere, 30% Wool", Style: "Open Front", Pockets: "Patch", Care: "Dry clean recommended" },
    },
    {
        id: "p17",
        name: "Classic Polo Shirt",
        slug: "classic-polo-shirt",
        description: "A wardrobe staple polo shirt made from premium pique cotton. Features a two-button placket, ribbed collar and cuffs, and a straight hem. Available in a range of colors.",
        shortDescription: "Premium pique cotton polo shirt",
        price: 59.99,
        originalPrice: undefined,
        discount: undefined,
        category: "men",
        brand: "StyleCo",
        images: [fashionImages.men[3], fashionImages.men[0], fashionImages.men[2]],
        rating: 4.3,
        reviewCount: 201,
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        colors: [
            { name: "White", hex: "#FFFFFF" },
            { name: "Navy", hex: "#1E3A5F" },
            { name: "Red", hex: "#EF4444" },
            { name: "Forest Green", hex: "#228B22" },
            { name: "Black", hex: "#141414" },
        ],
        stock: 110,
        stockPerVariant: { "M-White": 20, "L-Navy": 18, "M-Black": 15 },
        tags: ["polo", "shirt", "casual", "classic"],
        isBestSeller: true,
        material: "100% Pique Cotton",
        specifications: { Material: "100% Pique Cotton", Collar: "Ribbed", Fit: "Regular", Care: "Machine wash warm" },
    },
    {
        id: "p18",
        name: "Boho Maxi Skirt",
        slug: "boho-maxi-skirt",
        description: "A flowy bohemian maxi skirt with a tiered design and elastic waistband. Perfect for beach days or festival outfits. The lightweight fabric moves beautifully in the wind.",
        shortDescription: "Flowy tiered bohemian maxi skirt",
        price: 74.99,
        originalPrice: 99.99,
        discount: 25,
        category: "women",
        brand: "BellaMode",
        images: [fashionImages.women[1], fashionImages.women[3], fashionImages.women[2]],
        rating: 4.5,
        reviewCount: 88,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: [
            { name: "Terracotta", hex: "#E2725B" },
            { name: "Indigo", hex: "#4B0082" },
            { name: "Floral White", hex: "#FAFAFA" },
        ],
        stock: 43,
        stockPerVariant: { "S-Terracotta": 12, "M-Terracotta": 10, "S-Indigo": 8 },
        tags: ["skirt", "maxi", "boho", "summer"],
        isNew: true,
        material: "100% Rayon",
        specifications: { Material: "100% Rayon", Length: "Maxi", Waist: "Elastic", Care: "Machine wash gentle" },
    },
    {
        id: "p19",
        name: "Trail Running Shoes",
        slug: "trail-running-shoes",
        description: "Built for off-road adventures, these trail running shoes feature a grippy Vibram outsole, protective toe cap, and waterproof membrane. Aggressive lugs provide traction on any terrain.",
        shortDescription: "Waterproof trail running shoes with Vibram sole",
        price: 169.99,
        originalPrice: 219.99,
        discount: 23,
        category: "shoes",
        brand: "SwiftStep",
        images: [fashionImages.shoes[3], fashionImages.shoes[0], fashionImages.shoes[1]],
        rating: 4.8,
        reviewCount: 276,
        sizes: ["7", "8", "9", "10", "11", "12", "13"],
        colors: [
            { name: "Orange/Grey", hex: "#FF7043" },
            { name: "Black/Yellow", hex: "#1A1A1A" },
            { name: "Blue/Green", hex: "#1565C0" },
        ],
        stock: 54,
        stockPerVariant: { "10-Orange/Grey": 12, "9-Orange/Grey": 10, "11-Black/Yellow": 8 },
        tags: ["trail", "running", "outdoor", "waterproof"],
        isBestSeller: true,
        material: "Breathable Mesh, Vibram Outsole",
        specifications: { Upper: "Breathable Mesh", Sole: "Vibram", Protection: "Toe Cap", Waterproof: "Yes" },
    },
    {
        id: "p20",
        name: "Designer Sunglasses",
        slug: "designer-sunglasses",
        description: "Polarized sunglasses with UV400 protection and a lightweight acetate frame. The oversized square shape adds a modern fashion-forward touch to any look.",
        shortDescription: "Polarized UV400 acetate frame sunglasses",
        price: 189.99,
        originalPrice: undefined,
        discount: undefined,
        category: "accessories",
        brand: "LuxCraft",
        images: [fashionImages.accessories[0], fashionImages.accessories[2], fashionImages.accessories[1]],
        rating: 4.6,
        reviewCount: 142,
        sizes: ["One Size"],
        colors: [
            { name: "Tortoise", hex: "#8B4513" },
            { name: "Black", hex: "#141414" },
            { name: "Clear", hex: "#F5F5F5" },
        ],
        stock: 26,
        stockPerVariant: { "One Size-Tortoise": 10, "One Size-Black": 9 },
        tags: ["sunglasses", "accessories", "polarized", "uv400"],
        isFeatured: true,
        material: "Acetate Frame, Polarized Lens",
        specifications: { Frame: "Acetate", Lens: "Polarized", Protection: "UV400", Shape: "Oversized Square" },
    },
    // Additional products to reach 50+...
    {
        id: "p21",
        name: "Graphic Print Tee",
        slug: "graphic-print-tee",
        description: "100% organic cotton tee with a bold graphic print. The relaxed fit and crew neckline make it a versatile everyday essential.",
        shortDescription: "Organic cotton tee with bold graphic print",
        price: 39.99,
        originalPrice: undefined,
        discount: undefined,
        category: "men",
        brand: "UrbanEdge",
        images: [fashionImages.men[4], fashionImages.men[1]],
        rating: 4.2,
        reviewCount: 310,
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        colors: [{ name: "White", hex: "#FFFFFF" }, { name: "Black", hex: "#141414" }, { name: "Grey", hex: "#9CA3AF" }],
        stock: 130,
        stockPerVariant: { "M-White": 30, "L-White": 25, "M-Black": 20 },
        tags: ["tee", "graphic", "casual", "organic"],
        isBestSeller: true,
        material: "100% Organic Cotton",
        specifications: { Material: "100% Organic Cotton", Fit: "Relaxed", Neck: "Crew", Care: "Machine wash cold" },
    },
    {
        id: "p22",
        name: "Bomber Jacket",
        slug: "bomber-jacket",
        description: "Urban bomber jacket with a sleek silhouette, ribbed cuffs and hem, and a contrast lining. The zip front and side pockets complete the classic look.",
        shortDescription: "Classic urban bomber jacket with ribbed trim",
        price: 129.99,
        originalPrice: 169.99,
        discount: 24,
        category: "men",
        brand: "UrbanEdge",
        images: [fashionImages.men[0], fashionImages.men[2], fashionImages.men[4]],
        rating: 4.4,
        reviewCount: 177,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: [{ name: "Olive", hex: "#708238" }, { name: "Black", hex: "#141414" }, { name: "Navy", hex: "#1E3A5F" }],
        stock: 48,
        stockPerVariant: { "M-Olive": 12, "L-Black": 10, "M-Navy": 8 },
        tags: ["jacket", "bomber", "urban", "outerwear"],
        isNew: true,
        material: "Polyester Shell, Rayon Lining",
        specifications: { Shell: "100% Polyester", Lining: "Rayon", Closure: "Full Zip", Care: "Machine wash cold" },
    },
    {
        id: "p23",
        name: "Knit Beanie Hat",
        slug: "knit-beanie-hat",
        description: "Cozy ribbed knit beanie made from a soft acrylic-wool blend. Stretchy fit accommodates most head sizes. Perfect for outdoor activities in cold weather.",
        shortDescription: "Soft ribbed knit beanie for cold weather",
        price: 29.99,
        originalPrice: undefined,
        discount: undefined,
        category: "accessories",
        brand: "WoolCo",
        images: [fashionImages.accessories[2], fashionImages.accessories[0]],
        rating: 4.5,
        reviewCount: 224,
        sizes: ["One Size"],
        colors: [
            { name: "Camel", hex: "#C19A6B" }, { name: "Black", hex: "#141414" },
            { name: "Grey", hex: "#9CA3AF" }, { name: "Red", hex: "#EF4444" },
            { name: "Forest Green", hex: "#228B22" },
        ],
        stock: 180, stockPerVariant: {},
        tags: ["beanie", "hat", "winter", "accessories"],
        isBestSeller: true,
        material: "60% Acrylic, 40% Wool",
        specifications: { Material: "60% Acrylic, 40% Wool", Style: "Ribbed", Fit: "One Size Fits Most", Care: "Hand wash cold" },
    },
    {
        id: "p24",
        name: "Yoga Set (Top + Leggings)",
        slug: "yoga-set-top-leggings",
        description: "Matching yoga set with a butter-soft sports bra top and full-length leggings. Four-way stretch fabric and moisture-wicking technology keep you comfortable through any practice.",
        shortDescription: "Butter-soft matching yoga set",
        price: 89.99,
        originalPrice: 119.99,
        discount: 25,
        category: "women",
        brand: "ActiveWear",
        images: [fashionImages.women[0], fashionImages.women[2], fashionImages.women[4]],
        rating: 4.8,
        reviewCount: 415,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: [{ name: "Lavender", hex: "#E6E6FA" }, { name: "Dusty Rose", hex: "#DCAAB0" }, { name: "Black", hex: "#141414" }],
        stock: 72, stockPerVariant: { "S-Lavender": 15, "M-Black": 14, "L-Dusty Rose": 10 },
        tags: ["yoga", "set", "athletic", "leggings", "sports bra"],
        isBestSeller: true,
        material: "79% Polyester, 21% Spandex",
        specifications: { Material: "79% Polyester, 21% Spandex", Technology: "4-Way Stretch", Waistband: "High-Rise", Care: "Machine wash cold" },
    },
    {
        id: "p25",
        name: "Formal Dress Shirt",
        slug: "formal-dress-shirt",
        description: "Immaculately crafted dress shirt in premium poplin cotton. Features a French placket, spread collar, and a slim tailored fit. The non-iron fabric keeps you looking sharp all day.",
        shortDescription: "Non-iron poplin cotton dress shirt, slim fit",
        price: 99.99,
        originalPrice: undefined,
        discount: undefined,
        category: "men",
        brand: "StyleCo",
        images: [fashionImages.men[1], fashionImages.men[3], fashionImages.men[0]],
        rating: 4.4,
        reviewCount: 148,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: [{ name: "White", hex: "#FFFFFF" }, { name: "Sky Blue", hex: "#87CEEB" }, { name: "Pale Pink", hex: "#FFE4E1" }],
        stock: 65, stockPerVariant: { "M-White": 15, "L-White": 12, "M-Sky Blue": 10 },
        tags: ["dress shirt", "formal", "office", "poplin"],
        material: "100% Poplin Cotton",
        specifications: { Material: "100% Poplin Cotton", Collar: "Spread", Fit: "Slim", Care: "Machine wash, tumble dry low" },
    },
    {
        id: "p26", name: "Ribbed Tank Top", slug: "ribbed-tank-top",
        description: "Simple yet elevated ribbed tank top in a fitted silhouette. Versatile enough to wear solo or layer under everything.",
        shortDescription: "Fitted ribbed tank top for layering",
        price: 34.99, originalPrice: undefined, discount: undefined,
        category: "women", brand: "BellaMode",
        images: [fashionImages.women[2], fashionImages.women[0]],
        rating: 4.3, reviewCount: 289,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: [{ name: "White", hex: "#FFFFFF" }, { name: "Black", hex: "#141414" }, { name: "Sand", hex: "#C2B280" }],
        stock: 145, stockPerVariant: {},
        tags: ["tank top", "basics", "ribbed"],
        isBestSeller: true,
        material: "95% Cotton, 5% Spandex",
        specifications: { Material: "95% Cotton, 5% Spandex", Fit: "Fitted", Neck: "Scoop", Care: "Machine wash cold" },
    },
    {
        id: "p27", name: "Platform Sneakers", slug: "platform-sneakers",
        description: "Trendy platform sneakers with an extra-thick sole and chunky silhouette. The lace-up design and foam tongue padding ensure a comfortable fit.",
        shortDescription: "Chunky platform sneakers with thick sole",
        price: 119.99, originalPrice: 149.99, discount: 20,
        category: "shoes", brand: "FootFlair",
        images: [fashionImages.shoes[0], fashionImages.shoes[2], fashionImages.shoes[3]],
        rating: 4.4, reviewCount: 161,
        sizes: ["5", "6", "7", "8", "9", "10"],
        colors: [{ name: "White", hex: "#FFFFFF" }, { name: "Black", hex: "#141414" }, { name: "Pink/White", hex: "#FFB6C1" }],
        stock: 43, stockPerVariant: { "7-White": 10, "8-White": 8, "6-Pink/White": 6 },
        tags: ["sneakers", "platform", "chunky", "trendy"],
        isNew: true,
        material: "Synthetic Upper, Rubber Sole",
        specifications: { Upper: "Synthetic", Sole: "Rubber", Platform: "4cm", Care: "Wipe clean" },
    },
    {
        id: "p28", name: "Kids Denim Overalls", slug: "kids-denim-overalls",
        description: "Adorable denim overalls for kids with adjustable straps, snap crotch, and plenty of pockets. Durable and comfortable for everyday adventures.",
        shortDescription: "Classic denim overalls for active kids",
        price: 49.99, originalPrice: undefined, discount: undefined,
        category: "kids", brand: "TinyTrends",
        images: [fashionImages.kids[1], fashionImages.kids[0]],
        rating: 4.6, reviewCount: 94,
        sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
        colors: [{ name: "Light Wash", hex: "#B8D4E8" }, { name: "Dark Wash", hex: "#1B2A4A" }],
        stock: 62, stockPerVariant: {},
        tags: ["kids", "overalls", "denim", "casual"],
        material: "100% Cotton Denim",
        specifications: { Material: "100% Cotton Denim", Pockets: "4", Closure: "Snap Crotch", Care: "Machine wash cold" },
    },
    {
        id: "p29", name: "Structured Tote Bag", slug: "structured-tote-bag",
        description: "Sophisticated structured tote in vegan leather with a top zip closure, interior pockets, and detachable crossbody strap. Perfect for work or weekend.",
        shortDescription: "Vegan leather structured tote with crossbody strap",
        price: 149.99, originalPrice: 209.99, discount: 29,
        category: "accessories", brand: "LuxCraft",
        images: [fashionImages.accessories[2], fashionImages.accessories[0], fashionImages.accessories[1]],
        rating: 4.7, reviewCount: 198,
        sizes: ["One Size"],
        colors: [{ name: "Black", hex: "#141414" }, { name: "Camel", hex: "#C19A6B" }, { name: "White", hex: "#FFFFFF" }],
        stock: 31, stockPerVariant: {},
        tags: ["tote", "bag", "vegan leather", "work"],
        isFeatured: true,
        material: "Vegan Leather",
        specifications: { Material: "Vegan Leather", Closure: "Top Zip", Pockets: "Interior + Exterior", Strap: "Detachable" },
    },
    {
        id: "p30", name: "Fleece Pullover Hoodie", slug: "fleece-pullover-hoodie",
        description: "Essential fleece pullover hoodie with a kangaroo pocket, adjustable drawstring, and soft interior. A casual classic for layering all year round.",
        shortDescription: "Classic fleece pullover hoodie",
        price: 64.99, originalPrice: undefined, discount: undefined,
        category: "men", brand: "UrbanEdge",
        images: [fashionImages.men[2], fashionImages.men[4]],
        rating: 4.5, reviewCount: 431,
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        colors: [{ name: "Grey Heather", hex: "#B0B0B0" }, { name: "Navy", hex: "#1E3A5F" }, { name: "Black", hex: "#141414" }, { name: "Red", hex: "#EF4444" }],
        stock: 124, stockPerVariant: {},
        tags: ["hoodie", "fleece", "casual", "outerwear"],
        isBestSeller: true,
        material: "80% Cotton, 20% Polyester",
        specifications: { Material: "80% Cotton, 20% Polyester", Pocket: "Kangaroo", Hood: "Adjustable", Care: "Machine wash warm" },
    },
];

// -------- Categories --------
export const categories: Category[] = [
    { id: "c1", name: "Men", slug: "men", image: fashionImages.men[0], count: 145, description: "Explore our curated men's collection" },
    { id: "c2", name: "Women", slug: "women", image: fashionImages.women[0], count: 189, description: "Discover the latest women's fashion" },
    { id: "c3", name: "Kids", slug: "kids", image: fashionImages.kids[0], count: 67, description: "Fun and durable styles for little ones" },
    { id: "c4", name: "Accessories", slug: "accessories", image: fashionImages.accessories[0], count: 98, description: "Complete your look with our accessories" },
    { id: "c5", name: "Shoes", slug: "shoes", image: fashionImages.shoes[0], count: 112, description: "Step out in style with our footwear" },
    { id: "c6", name: "Sale", slug: "sale", image: fashionImages.women[3], count: 234, description: "Great deals on premium fashion" },
];

// -------- Reviews --------
export const reviews: Review[] = [
    { id: "r1", productId: "p1", userId: "u1", userName: "Michael S.", avatar: "https://i.pravatar.cc/50?img=11", rating: 5, title: "Best shirt I own", comment: "Incredibly comfortable and the quality is outstanding. I've washed it 20 times and it looks as good as new.", date: "2025-11-15", helpful: 34, verified: true },
    { id: "r2", productId: "p1", userId: "u2", userName: "James T.", avatar: "https://i.pravatar.cc/50?img=12", rating: 4, title: "Great fit, nice feel", comment: "True to size, very soft cotton. Minor quibble is the stitching on the collar pocket could be better.", date: "2025-10-28", helpful: 12, verified: true },
    { id: "r3", productId: "p3", userId: "u3", userName: "Sophia L.", avatar: "https://i.pravatar.cc/50?img=5", rating: 5, title: "Received SO many compliments!", comment: "Absolutely beautiful dress. The colors are vivid and it flows perfectly. Runs slightly large, size down.", date: "2025-12-01", helpful: 56, verified: true },
    { id: "r4", productId: "p5", userId: "u4", userName: "Alex K.", avatar: "https://i.pravatar.cc/50?img=20", rating: 5, title: "Game changer for runs", comment: "Wore these on a half marathon and my feet have never felt better. True to size, no break-in period needed.", date: "2025-11-20", helpful: 89, verified: true },
    { id: "r5", productId: "p6", userId: "u5", userName: "Emma W.", avatar: "https://i.pravatar.cc/50?img=9", rating: 5, title: "Worth every penny", comment: "The leather quality is phenomenal. It's the perfect size - not too big, not too small. Ships beautifully packaged.", date: "2025-09-17", helpful: 44, verified: true },
    { id: "r6", productId: "p12", userId: "u6", userName: "Chloe R.", avatar: "https://i.pravatar.cc/50?img=47", rating: 5, title: "Stunning watch", comment: "Exactly as pictured. The rose gold color is gorgeous and the leather strap feels luxurious. Keeping perfect time.", date: "2025-10-05", helpful: 61, verified: true },
];

// -------- Users --------
export const mockUsers: User[] = [
    {
        id: "u1",
        name: "Alex Johnson",
        email: "alex@example.com",
        avatar: "https://i.pravatar.cc/150?img=68",
        phone: "+1 (555) 123-4567",
        dob: "1992-05-15",
        addresses: [
            {
                id: "addr1", name: "Home",
                street: "123 Main Street, Apt 4B",
                city: "New York", state: "NY", zip: "10001", country: "United States",
                isDefault: true,
            },
        ],
    },
];

// -------- Orders --------
export const mockOrders: Order[] = [
    {
        id: "ORD-001",
        userId: "u1",
        items: [
            { productId: "p1", quantity: 2, price: 79.99, size: "M", color: "White" },
            { productId: "p5", quantity: 1, price: 149.99, size: "10", color: "White/Blue" },
        ],
        total: 309.97,
        status: "Delivered",
        date: "2025-11-10",
        trackingNumber: "1Z999AA1234567890",
        shippingAddress: {
            id: "addr1", name: "Home",
            street: "123 Main Street, Apt 4B",
            city: "New York", state: "NY", zip: "10001", country: "United States",
            isDefault: true,
        },
    },
    {
        id: "ORD-002",
        userId: "u1",
        items: [
            { productId: "p12", quantity: 1, price: 299.99, size: "One Size", color: "Rose Gold/Cream" },
        ],
        total: 299.99,
        status: "Shipped",
        date: "2025-12-01",
        trackingNumber: "1Z999AA9876543210",
        shippingAddress: {
            id: "addr1", name: "Home",
            street: "123 Main Street, Apt 4B",
            city: "New York", state: "NY", zip: "10001", country: "United States",
            isDefault: true,
        },
    },
    {
        id: "ORD-003",
        userId: "u1",
        items: [
            { productId: "p3", quantity: 1, price: 109.99, size: "S", color: "Floral Pink" },
            { productId: "p16", quantity: 1, price: 159.99, size: "S", color: "Oatmeal" },
        ],
        total: 269.98,
        status: "Processing",
        date: "2025-12-15",
        shippingAddress: {
            id: "addr1", name: "Home",
            street: "123 Main Street, Apt 4B",
            city: "New York", state: "NY", zip: "10001", country: "United States",
            isDefault: true,
        },
    },
];

// Brands
export const brands = ["StyleCo", "UrbanEdge", "BellaMode", "DenimLab", "SwiftStep", "FootFlair", "LuxCraft", "WoolCo", "TinyTrends", "TimeCraft", "ActiveWear"];

// Coupon codes
export const coupons: Record<string, { discount: number; type: "percent" | "fixed" }> = {
    SAVE10: { discount: 10, type: "percent" },
    WELCOME20: { discount: 20, type: "percent" },
    FLAT15: { discount: 15, type: "fixed" },
    KONAMI50: { discount: 50, type: "percent" },
};
